# -*- coding: utf-8 -*-
"""COVID-19 vs Happiness.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QAhIvbWSKp-rA9n4VbiMeXUBjnIlnDmZ
"""

# To analyse the relationship between COVID-19 and happiness
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

dataset = pd.read_csv("covid19_Confirmed_dataset.csv")
dataset.head()

# looking at the shape
dataset.shape

"""**Data Wrangling :**"""

# deleting unecessary columns
dataset.drop(["Lat", "Long"], axis=1, inplace=True)

# grouping data by country
agg_data = dataset.groupby("Country/Region").sum()
agg_data.head()

# visualising data by some countries in Asia
for country in ["China", "India", "Russia"]:
  agg_data.loc[country].plot()
plt.legend()

# calculating the first derivative of the curve
agg_data.loc["India"].diff().plot()

# maximum infection rate
agg_data.loc["India"].diff().max()



# finding infection rate of every country
infection_rates = []
for country in agg_data.index:
  infection_rates.append(agg_data.loc[country].diff().max())
agg_data["Max_infection_rate"] = infection_rates

agg_data

corona_data = pd.DataFrame(agg_data["Max_infection_rate"])
corona_data

"""**World Happiness Report**

---


"""

happiness = pd.read_csv("worldwide_happiness_report.csv")
happiness

"""**Data Wrangling**"""

happiness.drop(["Overall rank", "Generosity", "Perceptions of corruption"], axis=1, inplace=True)

happiness.head()

happiness.set_index("Country or region", inplace=True)

"""---

**COVID-19 vs Happiness**
"""

data = corona_data.join(happiness, how="inner")
data

# Correlation using Karl Pearson's method
data.corr()

x = data["GDP per capita"]
y = data["Max_infection_rate"]

sns.regplot(x=x, y=np.log(y))

x = data["Healthy life expectancy"]

sns.regplot(x=x, y=np.log(y))

"""**Insights**

Looking at the relationship between COVID-19 and happiness, we find that:


1.   Every aspect of the World Happiness Index shows a low, yet positive correlation with the number of COVID-19 cases.
2.   Among all the factors, the highest impact is seen on the healthy life expectancy.
3.   There was negligible impact on the Freedom to make life choices as per the dataset
"""